name: CI-build
run-name: CI-build

on:
  workflow_dispatch:
    branches:
      - main
    inputs:  
      gradle_debug_params:
        description: 'Gradle Debug Params'
        default: ''
        required: false
        type: string
  push:
    branches:
      - main
    paths:
      - src/**
      - gradle/*.gradle
      - build.gradle
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node_version: ${{ matrix.node_version }}
      - run: npm install
      - run: npm run unit
