name: CI-build
run-name: CI-build

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - src/**
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node_version: ${{ matrix.node_version }}
      - run: npm install
      - run: npm run test:unit
